### ISSUE TITLE
Avoid using const keyword in the polyfill to support IE9-10

### ISSUE THREAD

**Issue by soleo** [sodatea/get-current-script#2]
`const` will not work for IE11- 

This is an issue introduced in v1.0.1 11 days ago, not an issue in v1.0.0

https://caniuse.com/#search=const

**Comment by soleo** [comment]
@sodatea  Could you check this PR https://github.com/sodatea/get-current-script/issues/2? This is causing some issues for vue-cli-service

**Comment by soleo** [comment]
related to https://github.com/vuejs/vue-cli/pull/3760

**Comment by soleo** [comment]
Thanks!  @sodatea

**Comment by soleo** [comment]
Are you planning to do a patch release soon?

**Comment by haoqunjiang** [comment]
Yeah, v1.0.2 published
